title: All The Catz
email: tmetz@github.com
description: >- # this means to ignore newlines until "baseurl:"
  Gotta collect all the babies!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  cats:
    output: true
    order:
      - jabba-the-fluff.md
      - harvey.md
      - grumpy-cat.md
      - nala-cat.md
      - princess-monster-truck.md
